language: scala
scala:
  - 2.12.6

services:
  - mysql
  - docker

before_script:
  - sudo apt-get install redis
  - redis-server &

before_install:
  - docker-compose up

install:
  sbt reload update

script:
  - sbt test