language: scala
scala:
  - 2.12.6

before_script:
  - sudo apt-get install redis
  - redis-server &

before_install:
  - mysql -e 'CREATE DATABASE play_db;'

install:
  sbt reload update

script:
  - sbt test