db:
  container_name: container_db
  image: mysql:5.7
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=play_db

redis:
  container_name: container_redis
  image: redis

scala:
  container_name: container_scala_sbt
  image: bigtruedata/sbt
  links:
    - db
    - redis
  volumes:
    - "~/Desktop/scala_lab/myhttpakka:/app"