db:
  image: mysql:5.7
  ports:
    - "3306:3306"
  container_name: container_db
  environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    - MYSQL_DATABASE=play_db

redis:
  container_name: container_redis
  image: redis
  ports:
    - "6379:6379"